### PR TITLE
Make distro usable without Dist::Zilla

### PR DESCRIPTION
**Pull request by jjatria**
While Dist::Zilla is great for CPAN authors, it can make it hard for people to use a distribution's repository unless they have it installed, and installing it can sometimes be quite a hassle.

This commit makes it so that the repository is usable without having or using Dist::Zilla. This means that contributors can just contribute without worrying about authoring tools, and installers like cpanm can install directly from the repo without needing the authoring tool to build the distribution first.

### CODE REVIEW

**Review by JRaspass — CHANGES_REQUESTED** [review]
I agree, I think this 100% the way to go, dzil is useful for authors not users or committers, see also the recent pain from a BBC PoV - https://www.nntp.perl.org/group/perl.perl5.porters/2023/01/msg265492.html

Can you also drop the explicit test deps from the GH actions file then?
```yml
          install-modules: |
            Test2::Tools::Tiny
```

**Comment by jjatria** [comment]
@JRaspass And replace it with a pre-prove `cpanm --installdeps .` now that we can, you mean?

**Comment by JRaspass** [comment]
Does getting the action to do the work also work? Sounds like it would enable them to be cached.
```yml
  with:
    perl-version: ${{ matrix.perl }}
    install-modules-with: cpanm
```
From https://github.com/shogo82148/actions-setup-perl

**Comment by jjatria** [comment]
Worth a try. Let's see if the tests pass

**Review by allsopp — APPROVED** [review]

**Comment by jjatria** [comment]
I did a "squash and merge" because that seems to be the only way to do a fast-forward merge. Rare GH L

**Pull request merged**
